export function tryCatch(fn, onError) {
  try {
    return fn();
  } catch (e) {
    return onError(e);
  }
}
